<?php

namespace frontend\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the model class for table "users.user".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $created_at
 *
 * @property UsersInfo[] $usersInfos
 */

class User extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    //from UserInfo
    public $age;
    public $address;
    public $city;
    public $country;
    public $phone_number;
    //end from UserInfo
    public static function tableName()
    {
        return 'users.user';
    }

    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                ],
                'value' => new Expression('NOW()'),
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'email', 'password', 'age'], 'required'],
            [['created_at'], 'safe'],
            [['username'], 'string', 'max' => 63],
            [['email', 'password'], 'string', 'max' => 255],
            [['email'], 'email'],
            [['age'], 'integer'],
            [['address', 'city', 'country'], 'string', 'max' => 100],
            [['phone_number'], 'integer'],
            [['email', 'username'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'password' => 'Password',
            'created_at' => 'Created At',
            'age' => 'Age',
            'address' =>'Address',
            'city' => 'City',
            'country' => 'Country',
            'phone_number' =>'Phone Number'
        ];
    }

//    public function  afterSave($insert, $changedAttributes)
//    {
//         // TODO: Change the autogenerated stub
//        if($this->isNewRecord)
//        {
//            $user_info = new UsersInfo();
//            $user_info->user_id = $this->id;
//            $user_info->age = $this->age;
////            $user_info->address = $this->address;
////            $user_info->city = $this->city;
////            $user_info->country = $this->country;
////            $user_info->phone_number = $this->phone_number;
//            $user_info->save();
//        }else{
//            UsersInfo::updateAll(array(
//                'user_id' =>$this->id,
//                'age' => $this->age,
//                'address'=>$this->address,
//                'city'=>$this->city,
//                'country' => $this->city,
//                'phone_number'=>$this->phone_number
//            ), 'user_id=:user_id', array(':user_id'=> $this->id));
//        }
//        parent::afterSave($insert, $changedAttributes);
//    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsersInfo()
    {
        return $this->hasOne(UsersInfo::className(), ['user_id' => 'id']);
    }
}
